-- =========================================================
-- Extensions & UUID fallback
-- =========================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Fallback UUID generator:
-- Prefer uuidv7() if exists (provided by your own extension), otherwise gen_random_uuid()
CREATE OR REPLACE FUNCTION gen_uuid() RETURNS uuid AS $$
DECLARE v uuid;
DECLARE has_v7 boolean;
BEGIN
  SELECT EXISTS(SELECT 1 FROM pg_proc WHERE proname='uuidv7') INTO has_v7;
  IF has_v7 THEN
    EXECUTE 'SELECT uuidv7()' INTO v;
  ELSE
    v := gen_random_uuid();
  END IF;
  RETURN v;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- =========================================================
-- Tables
-- =========================================================

/*
    用户表：用户ID, 用户名, 邮箱, 密码哈希值, 头像链接, 创建时间, 修改时间
*/
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

/*
    角色表：角色ID, 角色名称(管理员/开发者/普通用户), 描述
*/
CREATE TABLE IF NOT EXISTS roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

/*
    权限定义表：权限ID, 权限标识符(如'app:publish', 'project:create'), 功能描述, 创建时间
*/
CREATE TABLE IF NOT EXISTS permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    角色-权限映射表：角色ID, 权限ID
*/
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id INTEGER REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id INTEGER REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

/*
    团体表：团体ID, 团体名称, 所有者ID, 团体类型, 创建时间
*/
CREATE TABLE IF NOT EXISTS groups (
    group_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    group_name VARCHAR(100) NOT NULL,
    owner_id UUID NOT NULL REFERENCES users(user_id),
    group_type VARCHAR(20) DEFAULT 'standard',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    成员-团体-角色映射表：团体ID, 用户ID, 角色ID
*/
CREATE TABLE IF NOT EXISTS group_members (
    group_id UUID REFERENCES groups(group_id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(user_id) ON DELETE CASCADE,
    role_id INTEGER REFERENCES roles(role_id),
    PRIMARY KEY (group_id, user_id)
);

/*
    应用市场表：应用ID, 应用名, 开发者ID, 分类, 标签, 元数据, 状态, 创建时间, 修改时间
*/
CREATE TABLE IF NOT EXISTS apps (
    app_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    name VARCHAR(255) NOT NULL,
    developer_id UUID NOT NULL REFERENCES users(user_id),
    category VARCHAR(50),
    tags TEXT[],
    metadata JSONB DEFAULT '{}'::jsonb,
    status VARCHAR(20) DEFAULT 'published', 
    create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_events (
    event_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    event_type VARCHAR(100) NOT NULL,
    trace_id VARCHAR(128),
    actor_id VARCHAR(128),
    resource VARCHAR(255),
    metadata JSONB DEFAULT '{}'::jsonb,
    error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_download_metrics (
    app_id UUID NOT NULL REFERENCES apps(app_id) ON DELETE CASCADE,
    metric_date DATE NOT NULL,
    download_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (app_id, metric_date)
);

CREATE TABLE IF NOT EXISTS minio_delete_retries (
    retry_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    object_name TEXT NOT NULL,
    reason TEXT,
    trace_id VARCHAR(128),
    attempts INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    next_run_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    用户项目表：项目ID, 项目名称, 所有者ID, 描述, 创建时间, 修改时间
*/
CREATE TABLE IF NOT EXISTS projects (
    project_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    name VARCHAR(255) NOT NULL,
    owner_id UUID NOT NULL REFERENCES users(user_id),
    description TEXT,
    create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    项目编排流程表：流程ID, 项目ID, 流程名称, 编排定义(JSONB), 修改时间
*/
CREATE TABLE IF NOT EXISTS project_workflows (
    workflow_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,
    workflow_name VARCHAR(100) NOT NULL,
    definition JSONB NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    项目资产表(用户文件)：资产ID, 项目ID, 资产名称, 资产类型, 存储URL, 校验和, 创建时间
*/
CREATE TABLE IF NOT EXISTS project_assets (
    asset_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,
    asset_name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(50),
    storage_url TEXT NOT NULL,
    checksum VARCHAR(64),
    file_size BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/*
    订阅授权表：订阅ID, 应用ID, 用户ID, 计划类型, 授权截止时间, 状态
    分区：按 expired_at 分区，保留复合主键以兼容既有业务
*/
CREATE TABLE IF NOT EXISTS subscriptions (
    sub_id UUID DEFAULT gen_uuid(),
    app_id UUID REFERENCES apps(app_id),
    user_id UUID REFERENCES users(user_id),
    plan_type VARCHAR(20),
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source_order_id UUID,
    status VARCHAR(10) DEFAULT 'active',
    PRIMARY KEY (sub_id, expired_at)
) PARTITION BY RANGE (expired_at);

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS source_order_id UUID;

-- 默认分区兜底，避免越界插入失败
CREATE TABLE IF NOT EXISTS subscriptions_default PARTITION OF subscriptions DEFAULT;

-- 近年滚动分区（按需扩展）
CREATE TABLE IF NOT EXISTS subscriptions_2025 PARTITION OF subscriptions
FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');
CREATE TABLE IF NOT EXISTS subscriptions_2026 PARTITION OF subscriptions
FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
CREATE TABLE IF NOT EXISTS subscriptions_2027 PARTITION OF subscriptions
FOR VALUES FROM ('2027-01-01') TO ('2028-01-01');
CREATE TABLE IF NOT EXISTS subscriptions_2028 PARTITION OF subscriptions
FOR VALUES FROM ('2028-01-01') TO ('2029-01-01');

/* =========================================================
   虚拟钱包表：钱包ID, 所有者ID(用户或团队), 余额, 币种
   ========================================================= */
CREATE TABLE IF NOT EXISTS wallets (
    wallet_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    owner_id UUID NOT NULL,
    owner_type VARCHAR(20) NOT NULL CHECK (owner_type IN ('user', 'group')),
    balance DECIMAL(18, 4) DEFAULT 0.0000,
    currency_code VARCHAR(10) DEFAULT 'COIN',
    status VARCHAR(20) DEFAULT 'active',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (owner_id, currency_code)
);

/* =========================================================
   虚拟货币流水表：流水ID, 钱包ID, 交易类型, 金额, 关联业务ID, 描述
   ========================================================= */
CREATE TABLE IF NOT EXISTS wallet_transactions (
    tx_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    wallet_id UUID REFERENCES wallets(wallet_id),
    tx_type VARCHAR(50) NOT NULL,
    amount DECIMAL(18, 4) NOT NULL,
    balance_after DECIMAL(18, 4) NOT NULL,
    reference_id UUID,
    idempotency_key TEXT UNIQUE,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

/* =========================================================
   订单表：应用购买/订阅前置订单，支付后关联钱包流水
   ========================================================= */
CREATE TABLE IF NOT EXISTS orders (
    order_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id),
    app_id UUID NOT NULL REFERENCES apps(app_id),
    wallet_id UUID NOT NULL REFERENCES wallets(wallet_id),
    amount DECIMAL(18, 4) NOT NULL CHECK (amount > 0),
    currency_code VARCHAR(10) NOT NULL DEFAULT 'COIN',
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled')),
    tx_id UUID REFERENCES wallet_transactions(tx_id),
    subscription_id UUID,
    idempotency_key TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS subscription_id UUID;

/* =========================================================
   权益发放 Outbox：支付事务提交后由后台消费者异步发放订阅权益
   ========================================================= */
CREATE TABLE IF NOT EXISTS entitlement_outbox (
    event_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    order_id UUID NOT NULL REFERENCES orders(order_id),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'done', 'failed')),
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_run_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    locked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id)
);

/* =========================================================
   优惠券定义表：记录优惠券的模板规则
   ========================================================= */
CREATE TABLE IF NOT EXISTS coupon_templates (
    template_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    name VARCHAR(100) NOT NULL,
    discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('fixed', 'percent')),
    discount_value DECIMAL(18, 4) NOT NULL,
    min_spend DECIMAL(18, 4) DEFAULT 0,
    valid_days INTEGER,
    target_app_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_coupon_templates_app') THEN
    ALTER TABLE coupon_templates
      ADD CONSTRAINT fk_coupon_templates_app
      FOREIGN KEY (target_app_id) REFERENCES apps(app_id);
  END IF;
END $$;

/* =========================================================
   用户/团队优惠券表：具体下发到账户的优惠券凭证
   ========================================================= */
CREATE TABLE IF NOT EXISTS coupons (
    coupon_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    template_id UUID REFERENCES coupon_templates(template_id),
    owner_id UUID NOT NULL,
    owner_type VARCHAR(20) NOT NULL CHECK (owner_type IN ('user', 'group')),
    status VARCHAR(20) DEFAULT 'unused' CHECK (status IN ('unused', 'used', 'expired')),
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    used_tx_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CHECK (expired_at > created_at)
);

/* =========================================================
   团队权益实例表 (Team Entitlements)
   ========================================================= */
CREATE TABLE IF NOT EXISTS group_entitlements (
    entitlement_id UUID PRIMARY KEY DEFAULT gen_uuid(),
    group_id UUID NOT NULL,
    benefit_code VARCHAR(100) NOT NULL,
    source_type VARCHAR(50),
    source_id UUID,
    expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) DEFAULT 'active'
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_entitlements_group') THEN
    ALTER TABLE group_entitlements
      ADD CONSTRAINT fk_entitlements_group
      FOREIGN KEY (group_id) REFERENCES groups(group_id);
  END IF;
END $$;

-- =========================================================
-- Indexes
-- =========================================================

-- JSONB 查询
CREATE INDEX IF NOT EXISTS idx_workflow_def ON project_workflows USING GIN (definition);

-- Projects
CREATE INDEX IF NOT EXISTS idx_project_owner ON projects(owner_id);
CREATE INDEX IF NOT EXISTS idx_workflows_project ON project_workflows(project_id);

-- Assets
CREATE INDEX IF NOT EXISTS idx_assets_project ON project_assets(project_id);

-- Group members
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_group_members_role ON group_members(role_id);

-- Apps
CREATE INDEX IF NOT EXISTS idx_apps_dev ON apps(developer_id);
CREATE INDEX IF NOT EXISTS idx_apps_tags ON apps USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_apps_name_trgm ON apps USING GIN (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_apps_status_create ON apps(status, create_at DESC);
CREATE INDEX IF NOT EXISTS idx_apps_status_category_create ON apps(status, category, create_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_apps_developer_idempotency_key
  ON apps(developer_id, (metadata ->> 'idempotency_key'))
  WHERE COALESCE(metadata ->> 'idempotency_key', '') <> '';

-- Audit & metrics
CREATE INDEX IF NOT EXISTS idx_audit_events_trace ON audit_events(trace_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_type_time ON audit_events(event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_app_download_metrics_date ON app_download_metrics(metric_date DESC, download_count DESC);
CREATE INDEX IF NOT EXISTS idx_minio_delete_retries_status_next ON minio_delete_retries(status, next_run_at);

-- Wallets & Transactions
CREATE INDEX IF NOT EXISTS idx_wallet_owner ON wallets(owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_wallet_status ON wallets(status);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet_time ON wallet_transactions(wallet_id, created_at DESC);

-- Orders
CREATE INDEX IF NOT EXISTS idx_orders_user_time ON orders(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_app_status ON orders(app_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_status_time ON orders(status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key
  ON orders(idempotency_key)
  WHERE COALESCE(idempotency_key, '') <> '';

-- Entitlement outbox
CREATE INDEX IF NOT EXISTS idx_entitlement_outbox_status_next ON entitlement_outbox(status, next_run_at);

-- Coupons
CREATE INDEX IF NOT EXISTS idx_coupons_owner_status ON coupons(owner_type, owner_id, status);
CREATE INDEX IF NOT EXISTS idx_coupons_template ON coupons(template_id);

-- Group entitlements
CREATE INDEX IF NOT EXISTS idx_group_entitlements_group ON group_entitlements(group_id);

-- Subscriptions
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_app ON subscriptions(user_id, app_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_subid ON subscriptions(sub_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_source_order ON subscriptions(source_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_default_order_once ON subscriptions_default(user_id, app_id, source_order_id) WHERE source_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_2025_order_once ON subscriptions_2025(user_id, app_id, source_order_id) WHERE source_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_2026_order_once ON subscriptions_2026(user_id, app_id, source_order_id) WHERE source_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_2027_order_once ON subscriptions_2027(user_id, app_id, source_order_id) WHERE source_order_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_2028_order_once ON subscriptions_2028(user_id, app_id, source_order_id) WHERE source_order_id IS NOT NULL;

-- =========================================================
-- Timestamp update triggers
-- =========================================================
CREATE OR REPLACE FUNCTION set_update_at() RETURNS trigger AS $$
BEGIN
  NEW.update_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- users.update_at
DROP TRIGGER IF EXISTS trg_users_update ON users;
CREATE TRIGGER trg_users_update BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_update_at();

-- apps.update_at
DROP TRIGGER IF EXISTS trg_apps_update ON apps;
CREATE TRIGGER trg_apps_update BEFORE UPDATE ON apps
FOR EACH ROW EXECUTE FUNCTION set_update_at();

-- projects.update_at
DROP TRIGGER IF EXISTS trg_projects_update ON projects;
CREATE TRIGGER trg_projects_update BEFORE UPDATE ON projects
FOR EACH ROW EXECUTE FUNCTION set_update_at();

-- project_workflows.update_at
DROP TRIGGER IF EXISTS trg_workflows_update ON project_workflows;
CREATE TRIGGER trg_workflows_update BEFORE UPDATE ON project_workflows
FOR EACH ROW EXECUTE FUNCTION set_update_at();

-- wallets.updated_at
DROP TRIGGER IF EXISTS trg_wallets_updated ON wallets;
CREATE TRIGGER trg_wallets_updated BEFORE UPDATE ON wallets
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- orders.updated_at
DROP TRIGGER IF EXISTS trg_orders_updated ON orders;
CREATE TRIGGER trg_orders_updated BEFORE UPDATE ON orders
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- entitlement_outbox.updated_at
DROP TRIGGER IF EXISTS trg_entitlement_outbox_updated ON entitlement_outbox;
CREATE TRIGGER trg_entitlement_outbox_updated BEFORE UPDATE ON entitlement_outbox
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- minio_delete_retries.updated_at
DROP TRIGGER IF EXISTS trg_minio_delete_retries_updated ON minio_delete_retries;
CREATE TRIGGER trg_minio_delete_retries_updated BEFORE UPDATE ON minio_delete_retries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- Seed data
-- =========================================================

/* 基础角色 */
INSERT INTO roles (role_id, role_name, description) VALUES
    (1, 'superadmin', '系统超级管理员，拥有全局最高权限'),
    (2, 'owner', '团体/项目所有者，拥有当前域内的所有权限'),
    (3, 'developer', '开发者，可以发布应用和创建项目编排'),
    (4, 'member', '普通成员，仅具备基本访问和运行权限')
ON CONFLICT (role_name) DO NOTHING;

SELECT setval(pg_get_serial_sequence('roles', 'role_id'), (SELECT COALESCE(MAX(role_id), 1) FROM roles));

/* 基础权限 */
INSERT INTO permissions (permission_code, description) VALUES
    ('app:create', '发布应用到市场'),
    ('app:edit', '编辑市场应用'),
    ('app:offshelf', '下架市场应用'),
    ('app:publish', '发布应用到市场'),
    ('app:delete', '删除市场应用'),
    ('app:subscribe', '订阅/购买应用'),
    ('project:create', '创建新项目'),
    ('project:edit', '编辑项目及编排'),
    ('project:delete', '删除项目'),
    ('group:invite', '邀请成员加入团体'),
    ('group:kick', '将成员移出团体'),
    ('group:view', '查看团体成员'),
    ('group:edit', '编辑团体'),
    ('group:delete', '删除团体'),
    ('role:manage', '管理角色与权限')
ON CONFLICT (permission_code) DO UPDATE SET description = EXCLUDED.description;

/* 绑定角色-权限映射 */
-- superadmin: 全部权限
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r, permissions p
WHERE r.role_name = 'superadmin'
ON CONFLICT DO NOTHING;

-- owner: 项目/群组相关 + 订阅
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r, permissions p
WHERE r.role_name = 'owner'
  AND p.permission_code IN (
    'group:view', 'group:edit', 'group:delete', 'group:invite', 'group:kick',
    'project:create', 'project:edit', 'project:delete', 'app:subscribe'
  )
ON CONFLICT DO NOTHING;

-- developer: 发布应用 + 项目编辑 + 订阅
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r, permissions p
WHERE r.role_name = 'developer'
  AND p.permission_code IN (
    'app:create', 'app:edit', 'app:offshelf', 'app:publish',
    'project:create', 'project:edit', 'app:subscribe'
  )
ON CONFLICT DO NOTHING;

-- member: 基础查看和订阅
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r, permissions p
WHERE r.role_name = 'member'
  AND p.permission_code IN ('group:view', 'app:subscribe')
ON CONFLICT DO NOTHING;

/* 默认管理员账户 */
INSERT INTO users (user_id, username, email, password_hash, is_active)
VALUES (
    '00000000-0000-0000-0000-000000000001', 
    'admin', 
    'admin@example.com', 
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 
    TRUE
)
ON CONFLICT DO NOTHING;

/* 默认系统团体/全局域 */
INSERT INTO groups (group_id, group_name, owner_id, group_type)
VALUES (
    '11111111-1111-1111-1111-111111111111', 
    'System Global Group', 
    '00000000-0000-0000-0000-000000000001', 
    'system'
)
ON CONFLICT (group_id) DO NOTHING;

/* 绑定管理员到系统团体，并赋予超级管理员角色 */
INSERT INTO group_members (group_id, user_id, role_id)
SELECT 
    '11111111-1111-1111-1111-111111111111',
    '00000000-0000-0000-0000-000000000001',
    r.role_id
FROM roles r
WHERE r.role_name = 'superadmin'
ON CONFLICT DO NOTHING;
