auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki

  # 👇 新增这部分配置，强行指定单机使用 memberlist / in-memory，防止它去找 Consul
  ring:
    kvstore:
      store: memberlist

  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-bucket
      access_key_id: ${MINIO_ROOT_USER}
      secret_access_key: ${MINIO_ROOT_PASSWORD}
      s3forcepathstyle: true
  compactor_address: http://loki:3100
  replication_factor: 1

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index
    cache_location: /tmp/loki/tsdb-cache

compactor:
  working_directory: /tmp/loki/compactor
