brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 开启自动创建 Topic，开发环境必备
autoCreateTopicEnable = true

# ！！！非常重要：如果是本地开发，请设置为 127.0.0.1 
# 如果是服务器部署，请设置为服务器公网/局域网 IP
brokerIP1 = 172.18.0.1
